version: '3.7'

# -----------------------------------------------------------------------------
# Generate configs to use inside containers within Swarm
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Generate secrets to use inside containers within Swarm
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Specify named volumes to use with containers
# -----------------------------------------------------------------------------

volumes:
  ignore:
  pgadmin:

# -----------------------------------------------------------------------------
# Specify additional networks
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Setup anchors and aliases
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Specify all services to deploy
# -----------------------------------------------------------------------------

services:

  client:
    build:
      context: ./client
      target: production
    ports:
      - "80:3000"
      - "81:80"
    environment:
      - NODE_ENV=development
      # Allows you to use any host like lvh.me and others
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      # Enables live reload inside VM or Docker
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client/src:/opt/app/src
      - ./client/public:/opt/app/public

  app:
    build:
      context: ./app
      target: development
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PGHOST=api.salt.promoresolution.com
    volumes:
      - ./app:/opt/app:delegated

  postgres:
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "85:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecretPasswrd